### ISSUE TITLE
Is it down?

### ISSUE THREAD

**Issue by rubengamboa** [calebegg/proof-pad#26]
Hi, Caleb. Is ProofPad completely down right now? I just get socket connection issues. Thanks.

**Comment by rubengamboa** [comment]
Hi, Caleb.

I actually moved back to ProofPad1 I like my Jupyter images, but ProofPad is much nicer for the students. Next week is fine — don’t stress about it.

I'd offer to help with the problems, but I’m afraid I don’t know GCP at all. What is a containerd image?

Thanks!

Clear skies,
Ruben

--
Ruben Gamboa
Professor
Electrical Engineering and Computer Science
University of Wyoming

**Comment by calebegg** [comment]
Oh, that's cool, I didn't know that. I'll try to keep a closer eye on it going forward.

[Here's the documentation about the containerd](https://cloud.google.com/kubernetes-engine/docs/deprecations/docker-containerd) migration but I can totally do it.

Rotating the credentials actually looks like it's the more likely issue, since they just expired yesterday. I'll take a 30 minute pass at it this afternoon and see if it's easy.

**Comment by calebegg** [comment]
Seems like that worked. Thanks for letting me know about the issue.
